name: DHTxx Automatic Build

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        example:
          - examples/dhtxx_example.cpp
        target_device:
          - d1_mini
          - esp32dev
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Set up Python
        uses: actions/setup-python@v1
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install platformio
      - name: Run PlatformIO
        run: platformio ci -v --lib . -c ci/platformio.ini
        env:
          PLATFORMIO_CI_SRC: ${{ matrix.example }}
          CI_TARGET_DEVICE: ${{ matrix.target_device }}
